netlify.toml
resolves #12
Cherry picked from https://github.com/vuejs/docs/commit/57291ec746dbde57b8bcc60662a9ab06ef99c04d
=> remove no longer necessary pnpm netlify config (#12)

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue
resolves #16
Cherry picked from https://github.com/vuejs/docs/commit/ee975453c0e4547831123051b4b1645f967fc926
=> Change text to reflect remote event (#16)

src/about/team/TeamList.vue
resolves #24
Cherry picked from https://github.com/vuejs/docs/commit/7e9f1e642b48de5cfd412d0fb932209181124599
=> fix: TeamList.vue sticky info (#24)

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
resolves #31
Cherry picked from https://github.com/vuejs/docs/commit/73661d8ee6d486a830130870032ac06ee1ab06c4
=> remove vue toronto banner (#31)

src/guide/extras/render-function.md
resolves #35
Cherry picked from https://github.com/vuejs/docs/commit/7826a0167ef1236a3aadf2c24c0587935e853da1
=> Explain attribute inheritance for functional components (#35)

src/about/team/TeamList.vue
resolves #40
Cherry picked from https://github.com/vuejs/docs/commit/92df83d857189157ee1f1094ad0c4b50337e38da
=> Fix Team sticky headers (#40)

src/about/team/TeamList.vue, src/api/reactivity-utilities.md, src/guide/essentials/watchers.md
resolves #44
Cherry picked from https://github.com/vuejs/docs/commit/381861a14fde1339e8b68ba77cb19533b77869f5
=> Add computed refs to isReadonly (#44)

src/api/application.md
Added docs translation before the app.component() part
English version
Translated
=> Translation of the Application API topic

src/guide/scaling-up/sfc.md
Перевод раздела Single-File Components
=> Translation of the SFC topic

src/api/ApiIndex.vue, src/api/api.data.ts
resolves #66
Cherry picked from https://github.com/vuejs/docs/commit/11bd76fa9a3e01cea60257af77c23645fcb4008d
=> Fix API index heading text (#66)

src/about/faq.md
resolves #69
Cherry picked from https://github.com/vuejs/docs/commit/460f55a1324b904eb9446534aa7599319765c789
=> FAQ tweaks (#69)

src/translations/index.md
resolves #71
Cherry picked from https://github.com/vuejs/docs/commit/9e0fc14876175332a4de043a47cdd43e68ead0bb
=> feat: add french translations repo link (#71)

src/about/team/members-core.json
resolves #75
Cherry picked from https://github.com/vuejs/docs/commit/2f436c6451974c45195738fe10f7ef3b69ce7bf6
=> chore: update team member (#75)

src/about/team/members-partner.json
resolves #77
Cherry picked from https://github.com/vuejs/docs/commit/117f19329a4983e992e808c7a07acedee7251925
=> chore: update partner's company after rebranding (#77)

src/guide/components/async.md
resolves #79
Cherry picked from https://github.com/vuejs/docs/commit/39e9e0e1b3b9c35f2bee068f0e77e59130fdff88
=> update to a correct link for dynamic imports (#79)

src/partners/partners.json
resolves #87
Cherry picked from https://github.com/vuejs/docs/commit/f42130066dbdd0f49b2a0d25965dfd65fe84e814
=> update jump24 url (#87)

package.json, pnpm-lock.yaml
resolves #90
Cherry picked from https://github.com/vuejs/docs/commit/3b93dce468d2a27d2ec0ca43d7f1335352861097
=> bump deps (#90)

src/guide/extras/web-components.md, src/guide/scaling-up/ssr.md
resolves #96
Cherry picked from https://github.com/vuejs/docs/commit/4d0e455602b96b68d0c08ecc3ba8b0490c58ff57
=> chore: update link to ssr-vue playground (#96)

src/guide/extras/ways-of-using-vue.md, src/guide/scaling-up/ssr.md
resolves #100
Cherry picked from https://github.com/vuejs/docs/commit/008c9abe27b2a5e2850f96d62d1a6202397278f2
=> update Nuxt url (#100)

src/about/team/members-core.json
resolves #103
Cherry picked from https://github.com/vuejs/docs/commit/051d926a4bcafd9037d7e1a650725e19bf044fd3
=> Fix broken portal-vue link (#103)

src/guide/essentials/reactivity-fundamentals.md
resolves #109
Cherry picked from https://github.com/vuejs/docs/commit/698856aa9a4babb5a0915b9d7e2992c2d24706a9
=> Fix a grammatical mistake (#109)

src/guide/best-practices/accessibility.md, src/guide/essentials/template-refs.md
resolves #117
Cherry picked from https://github.com/vuejs/docs/commit/f634c9b719a4e8706fd150c5fb12b84ee57d0131
=> Add a comment about not importing defineExpose (#117)

src/api/api.data.ts
resolves #120
Cherry picked from https://github.com/vuejs/docs/commit/262b5a17b324bc82567fbe4fa1c8abd90e7fb458
=> Removed unnecessary escape character (#120)

src/guide/components/registration.md
Частично текст перенесен из существующей документации https://v3.ru.vuejs.org/ru/guide/component-registration.html
=> Translation of /guide/components/registration  page

.vitepress/config.ts, src/guide/built-ins/teleport.md
resolves https://github.com/translation-gang/docs-ru/issues/142
=> Локализация - guide/built-ins/teleport.md

src/api/application.md
Отсутствие перевода на странице api/application.md
Добавлена локализация для выше указанной страницы
resolves #217
=> (fix): Локализация -  api/application.md

src/api/ssr.md
Отсутствие перевода на странице api/ssr.md
resolved #254
=> (fix): Локализация - api/ssr.md 

src/api/sfc-script-setup.md
Отсутствие перевода на странице api/sfc-script-setup.md
resolved #248
=> (fix): Локализация - api/sfc-script-setup.md

src/api/utility-types.md
Отсутствие перевода на странице api/utility-types.md 
resolved #256
=> (fix): Локализация - api/utility-types.md 

src/api/sfc-css-features.md
Отсутствие перевода на странице api/sfc-css-features.md
resolved #250
=> (fix): Локализация - api/sfc-css-features.md

src/guide/extras/ways-of-using-vue.md
Отсутсвие перевода на странице /guide/extras/ways-of-using-vue.html
Добавлена локализация для выше указанной страницы
resolves #195
=> (fix): Локализация - guide/extras/ways-of-using-vue

src/api/custom-renderer.md
Отсутствие перевода на странице api/custom-renderer.md
resolved #258
=> (fix): Локализация - api/custom-renderer.md

src/tutorial/src/step-9/App/template.html, src/tutorial/src/step-9/_hint/App/composition.js, src/tutorial/src/step-9/_hint/App/options.js, src/tutorial/src/step-9/description.md
Отсутствие перевода на странице tutorial/src/step-9/description.md
Добавлена локализация для выше указанной страницы
resolves #201
=> (fix): Локализация - tutorial/src/step-9/description.md

src/examples/src/cells/store.js, src/examples/src/circle-drawer/App/template.html, src/examples/src/counter/App/template.html, src/examples/src/crud/App/composition.js, src/examples/src/crud/App/options.js, src/examples/src/crud/App/template.html, src/examples/src/flight-booker/App/composition.js, src/examples/src/flight-booker/App/options.js, src/examples/src/flight-booker/App/template.html, src/examples/src/temperature-converter/App/template.html, src/examples/src/timer/App/template.html
Отсутсвие перевода блока 7 GUIs на странице /examples.html
Добавлена локализация для выше указанного блока
resolves #225
=> (fix): Локализация - /examples 7 GUIs

src/examples/src/attribute-bindings/App/composition.js, src/examples/src/attribute-bindings/App/options.js, src/examples/src/attribute-bindings/App/template.html, src/examples/src/attribute-bindings/description.txt, src/examples/src/conditionals-and-loops/App/template.html, src/examples/src/conditionals-and-loops/description.txt, src/examples/src/form-bindings/App/composition.js, src/examples/src/form-bindings/App/options.js, src/examples/src/form-bindings/App/template.html, src/examples/src/form-bindings/description.txt, src/examples/src/handling-input/App/composition.js, src/examples/src/handling-input/App/options.js, src/examples/src/handling-input/App/template.html, src/examples/src/handling-input/description.txt, src/examples/src/hello-world/App/composition.js, src/examples/src/hello-world/App/options.js, src/examples/src/hello-world/description.txt, src/examples/src/simple-component/App/template.html, src/examples/src/simple-component/description.txt
Отсутсвие перевода блока Basic на странице /examples.html
Добавлена локализация для выше указанного блока
resolves #216
=> (fix): Локализация - /examples basic

src/guide/typescript/composition-api.md
Отсутсвие перевода на странице /guide/typescript/composition-api.html
Добавлена локализация для выше указанной страницы
resolves #191
=> (fix): Локализация - guide/typescript/composition-api

.gitignore
Закрывает https://github.com/translation-gang/docs-ru/issues/271
Обновляет .gitignore
=> (fix) Рутина - обновить .gitignore

.vitepress/config.ts, .vitepress/theme/components/Banner.vue, .vitepress/theme/components/NewsLetter.vue, .vitepress/theme/components/PreferenceTooltip.vue, .vitepress/theme/components/ReplLoading.vue, .vitepress/theme/components/TextAd.vue, .vitepress/theme/components/VueMasteryModal.vue
=> feat Перевод в директории .vitepress

src/ecosystem/newsletters.md
feat: add translation for page Newsletters.md
Issues - https://github.com/translation-gang/docs-ru/issues/291
=> feat: add translation for page Newsletters.md

src/guide/typescript/composition-api.md
связано с #279 
PS. Провел ресерч.
"Типизирование чего-то" - как термин супер редкий (286 совпадений в гугле)
"Типизация чего-то" - встречается чаще (20к+ совпадений в гугле)
=> feat Обновление переводов для composition-api

src/guide/extras/web-components.md
Отсутствие  части перевода на странице guide/extras/web-components.md
resolved #282
=> (fix): Локализация - guide/extras/web-components.md

src/guide/quick-start.md
Отсутствие части перевода на странице guide/quick-start.md
resolved #284
=> (fix): Локализация - guide/quick-start.md

src/api/built-in-special-elements.md
Отсутствие части перевода на странице api/built-in-special-elements.md
resolved #285
=> (fix): Локализация - api/built-in-special-elements.md

.vitepress/config.ts, src/style-guide/rules-essential.md
Нет перевода для https://vuejs.org/style-guide/rules-essential.html
Сделал перевод для https://vuejs.org/style-guide/rules-essential.html
resolved #293
=> feat: translate a-rules

src/style-guide/index.md
Нет перевода для https://vuejs.org/style-guide/
Сделал перевод для https://vuejs.org/style-guide/
resolved #292
=> feat: translate style guide index page

src/api/sfc-script-setup.md
Нет перевода для https://vuejs.org/api/sfc-script-setup.html
Есть перевод для https://vuejs.org/api/sfc-script-setup.html
resolve #289
=> feat: start translate sfc-script-setup.md

src/about/coc.md
Нет перевода для https://vuejs.org/about/coc
Есть перевод для https://vuejs.org/about/coc
resolved #317
=> feat: translate coc.md

src/api/sfc-script-setup.md
Правка #343
Пункт: "[SFC Script setup (там продублирован текст на строке 287, нужно исправить)](https://github.com/translation-gang/docs-ru/blob/main/src/api/sfc-script-setup.md)"
=> fix Убран оставленный перевод

src/guide/essentials/lifecycle.md
Issue: https://github.com/translation-gang/docs-ru/issues/341
=> Фикс перевода внизу страницы guide/essentials/lifecycle

src/about/faq.md
Нет перевода для https://vuejs.org/about/faq.html
Есть перевод для https://vuejs.org/about/faq.html
resolved #319
=> feat: translate faq.md

src/api/composition-api-dependency-injection.md
Закончен перевод для страницы #287
=> feat: translate new blocks on the `composition-api-dependency-injection` page

src/examples/src/list-transition/App/style.css, src/examples/src/modal/Modal/style.css
Были недопереведены некоторые элементы в блоках:
* /examples/list-transition
* /examples/modal
Добавлен перевод
=> translate: blocks in /examples/list-transition, /examples/modal

.vitepress/config.ts
feat(search) Connecting Algolia search
=> feat(search) Connecting Algolia search

src/guide/components/provide-inject.md
Исправления грамматики в разделе "Provide / Inject"
=> fix: correct spelling mistakes in provide-inject.md

src/guide/components/async.md
Добавил перевод фрагмента текста на русский язык
=> fix: add translation in async.md

.vitepress/theme/components/Home.vue, .vitepress/theme/components/SecurityUpdateBtn.vue, .vitepress/theme/index.ts
=> Обновление исходников

src/guide/essentials/list.md
add block for options api
block missing for options api
add block for options api
=> add block for options api

src/api/application.md
Обновлен перевод в application.md
=> feat(docs): Update translations in application.md

src/guide/reusability/custom-directives.md
correction of a typo in the text
=> feat(docs): Update translations in custom-directives.md

src/guide/quick-start.md
=> Исправлено грамматическая ошибка

src/guide/built-ins/transition-group.md
отсутствовал перевод части раздела TransitionGroup
добавлен перевод части раздела TransitionGroup
=> Добавлен перевод части раздела TransitionGroup
